function powerline_precmd() {
    PS1="$(powerline-shell --shell zsh $?)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	# git
	# gitfast
	# poetry
	zsh-autosuggestions
	zsh-fzf-history-search
	zsh-syntax-highlighting # must be last plugin sourced
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

if [[ $(uname) == "Linux" ]]; then
    alias update="sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade"

    # keyboard
    alias xpskb='setxkbmap -layout "dvorak" -option "ctrl:swapcaps"'
    alias ergkb='setxkbmap -layout "us" -option'

    # monitors
    alias home_screen="xrandr --output eDP-1 --off --output DP-1 --mode 3840x2160"  
    alias upstate_screen="xrandr --output eDP-1 --off --output DP-1 --mode 2560x1440 --scale 1.5x1.5"
    alias xps_screen="xrandr --output eDP-1 --mode 3200x1800 --output DP-1 --off"
    alias precision_screen="xrandr --output eDP-1 --mode 3840x2160"

    # helpers
    alias desktop="ergkb && home_screen"
    alias upstate="ergkb && upstate_screen"
    alias xps="xpskb && xps_screen"
    alias precision="xpskb && precision_screen"
elif [[ $(uname) == "Darwin" ]]; then
    alias update="brew update && brew upgrade"
fi

# bash
alias ll='ls -alh'
alias la='ls -A'
alias l='ls -CFlh'
alias lsd="ls -alF | grep /$"

# git
alias gs="git status"
alias gc="git checkout"
alias gsc="git switch --create"
alias gd="git diff"
alias ga="git add"
alias gcm="git commit -m"
alias gcam="git commit -am"
alias gl="git log --oneline --graph --decorate"

# tmux
alias tmux="tmux -2"
alias ta="tmux attach"

# nvim
alias vi="nvim"

setopt completealiases

# needed for fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# needed for nvcc
export PATH=$PATH:/usr/local/cuda/bin

# needed for pyenv and pyenv-virtualenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"   # temporarily disable because it slows down zsh on mac os

# do not generate pycache
export PYTHONDONTWRITEBYTECODE=1

# needed by lua-language-server
alias luamake=/home/gianluca/git/lua-language-server/3rd/luamake/luamake

# needed by rust
export PATH=$PATH:$HOME/.cargo/env

# needed by poetry
if [[ $(uname) == "Linux" ]]; then
    export PATH="/home/gianluca/.local/bin:$PATH"
elif [[ $(uname) == "Darwin" ]]; then
    export PATH="/Users/gianluca/.local/bin:$PATH"
else
    echo "Unknown OS. Could not add Poetry executable's path to PATH"
fi
path+=~/.zfunc
autoload -Uz compinit && compinit
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

# needed by dwmblocks
export PATH=$PATH:~/.local/bin/statusbar/
