# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	# git
	# gitfast
	# poetry
	zsh-vi-mode
	fzf
	zsh-autosuggestions
	direnv
	zsh-syntax-highlighting # must be last plugin sourced
)

ZVM_INIT_MODE=sourcing
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

if [[ $(uname) == "Linux" ]]; then
    alias update="sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade"

    # keyboard
    alias xpskb='setxkbmap us -variant dvorak -option ctrl:swapcaps'
    alias ergkb='setxkbmap -layout "us" -option'

    # monitors
    alias home_screen="xrandr --output eDP-1 --off --output DP-1 --mode 3840x2160"  
    alias upstate_screen="xrandr --output eDP-1 --off --output DP-1 --mode 2560x1440 --scale 1.5x1.5"
    alias xps_screen="xrandr --output eDP-1 --mode 3200x1800 --output DP-1 --off"
    alias precision_screen="xrandr --output eDP-1 --mode 3840x2160"

    # helpers
    alias desktop="ergkb && home_screen"
    alias upstate="ergkb && upstate_screen"
    alias xps="xpskb && xps_screen"
    alias precision="xpskb && precision_screen"
elif [[ $(uname) == "Darwin" ]]; then
    alias update="brew update && brew upgrade"
fi

# bash
alias ll='ls -alh'
alias la='ls -A'
alias l='ls -CFlh'
alias lsd="ls -alF | grep /$"

# git
alias gs="git status"
alias gc="git checkout"
alias gsc="git switch --create"
alias gd="git diff"
alias ga="git add"
alias gcm="git commit -m"
alias gcam="git commit -am"
alias gl="git log --oneline --graph --decorate"

# tmux
alias tmux="tmux -2"
alias ta="tmux attach"

# nvim
alias vi="nvim"

setopt completealiases

# needed for nvcc
export PATH=$PATH:/usr/local/cuda/bin

# do not generate pycache
export PYTHONDONTWRITEBYTECODE=1

# use ipdb as interactive debugger
export PYTHONBREAKPOINT=ipdb.set_trace

# needed by lua-language-server
alias luamake=/home/gianluca/git/lua-language-server/3rd/luamake/luamake

# source binaries needed by dwmblocks
export PATH=$PATH:~/.local/bin/statusbar/

# To customize prompt, run `p10k configure` or edit ~/.dotfiles/zsh/p10k.zsh.
[[ ! -f ~/.dotfiles/zsh/p10k.zsh ]] || source ~/.dotfiles/zsh/p10k.zsh

# needed by rust
. "$HOME/.cargo/env"

# needed by uv-python
. "$HOME/.local/bin/env"

# rose-pine theme for fzf
export FZF_DEFAULT_OPTS="
	--color=fg:#908caa,bg:#191724,hl:#ebbcba
	--color=fg+:#e0def4,bg+:#26233a,hl+:#ebbcba
	--color=border:#403d52,header:#31748f,gutter:#191724
	--color=spinner:#f6c177,info:#9ccfd8
	--color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"
